import type { BenchmarkResult, HardwareProfile, PricingTier } from "@/types";

export const BENCHMARKS: BenchmarkResult[] = [
  {
    id: "b1",
    model: "Llama-3-8B",
    modelSize: "8B",
    hardware: "Jetson Orin Nano",
    tokensPerSec: 38,
    latencyMs: 26,
    energyW: 9.2,
    accuracyPct: 98.8,
    technique: "INT4 + TensorRT",
    runtime: "llama.cpp",
    validated: true,
    peerReviewed: true,
    publishedAt: "2024-11-14",
    author: "rafael.lima",
    upvotes: 412,
    tags: ["int4", "tensorrt", "jetson", "llm"],
  },
  {
    id: "b2",
    model: "Phi-3 Mini",
    modelSize: "3.8B",
    hardware: "Raspberry Pi 5",
    tokensPerSec: 14,
    latencyMs: 71,
    energyW: 4.8,
    accuracyPct: 97.1,
    technique: "GGUF Q4_K_M",
    runtime: "llama.cpp",
    validated: true,
    peerReviewed: false,
    publishedAt: "2024-12-01",
    author: "ana.souza",
    upvotes: 289,
    tags: ["gguf", "raspberry", "slm", "offline"],
  },
  {
    id: "b3",
    model: "Gemma-2B",
    modelSize: "2B",
    hardware: "Raspberry Pi 5",
    tokensPerSec: 22,
    latencyMs: 45,
    energyW: 3.9,
    accuracyPct: 95.4,
    technique: "INT8 + XNNPACK",
    runtime: "TFLite",
    validated: true,
    peerReviewed: true,
    publishedAt: "2024-10-20",
    author: "pedro.alves",
    upvotes: 198,
    tags: ["int8", "tflite", "raspberry", "slm"],
  },
  {
    id: "b4",
    model: "Mistral-7B",
    modelSize: "7B",
    hardware: "Jetson AGX Orin",
    tokensPerSec: 62,
    latencyMs: 16,
    energyW: 22.1,
    accuracyPct: 99.2,
    technique: "FP16 + TensorRT",
    runtime: "TensorRT-LLM",
    validated: true,
    peerReviewed: true,
    publishedAt: "2024-09-30",
    author: "juliana.costa",
    upvotes: 531,
    tags: ["fp16", "tensorrt", "jetson", "llm"],
  },
  {
    id: "b5",
    model: "TinyLlama-1.1B",
    modelSize: "1.1B",
    hardware: "ESP32-S3",
    tokensPerSec: 2,
    latencyMs: 500,
    energyW: 0.24,
    accuracyPct: 81.3,
    technique: "INT4 + Custom SIMD",
    runtime: "llama.cpp (bare metal)",
    validated: false,
    peerReviewed: false,
    publishedAt: "2024-12-10",
    author: "marcos.vieira",
    upvotes: 87,
    tags: ["int4", "mcu", "esp32", "ultra-low-power"],
  },
  {
    id: "b6",
    model: "YOLOv8n",
    modelSize: "3.2MB",
    hardware: "STM32H7",
    tokensPerSec: 0,
    latencyMs: 12,
    energyW: 0.045,
    accuracyPct: 89.3,
    technique: "INT8 + CMS-NN",
    runtime: "STM32Cube.AI",
    validated: true,
    peerReviewed: true,
    publishedAt: "2024-08-15",
    author: "camila.rocha",
    upvotes: 673,
    tags: ["vision", "mcu", "object-detection", "cms-nn"],
  },
  {
    id: "b7",
    model: "Llama-3-70B",
    modelSize: "70B",
    hardware: "Jetson AGX Orin (x2)",
    tokensPerSec: 18,
    latencyMs: 55,
    energyW: 58.0,
    accuracyPct: 99.9,
    technique: "INT4 + Pipeline Parallel",
    runtime: "vLLM + TensorRT",
    validated: true,
    peerReviewed: true,
    publishedAt: "2024-11-28",
    author: "thiago.mendes",
    upvotes: 944,
    tags: ["int4", "multi-device", "jetson", "llm", "large"],
  },
  {
    id: "b8",
    model: "Whisper-Small",
    modelSize: "244MB",
    hardware: "Raspberry Pi 5",
    tokensPerSec: 0,
    latencyMs: 320,
    energyW: 5.1,
    accuracyPct: 96.8,
    technique: "INT8 + ONNX",
    runtime: "ONNX Runtime",
    validated: true,
    peerReviewed: false,
    publishedAt: "2024-10-05",
    author: "beatriz.santos",
    upvotes: 154,
    tags: ["audio", "asr", "raspberry", "onnx"],
  },
];

export const HARDWARE_PROFILES: HardwareProfile[] = [
  { id: "jetson-orin-nano", name: "Jetson Orin Nano", category: "jetson", ram: "8 GB", tdp: "10W", chip: "Ampere 1024-core" },
  { id: "jetson-agx-orin", name: "Jetson AGX Orin", category: "jetson", ram: "64 GB", tdp: "60W", chip: "Ampere 2048-core" },
  { id: "rpi5", name: "Raspberry Pi 5", category: "raspberry", ram: "8 GB", tdp: "5W", chip: "Cortex-A76" },
  { id: "esp32s3", name: "ESP32-S3", category: "mcu", ram: "512 KB", tdp: "0.3W", chip: "Xtensa LX7" },
  { id: "stm32h7", name: "STM32H7", category: "mcu", ram: "1 MB", tdp: "0.05W", chip: "Cortex-M7" },
  { id: "m2-macbook", name: "MacBook Pro M2", category: "pc", ram: "32 GB", tdp: "20W", chip: "Apple M2 Pro" },
];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: "free",
    name: "Free",
    price: { monthly: 0, annual: 0 },
    description: "Para explorar e validar a plataforma",
    cta: "Começar grátis",
    highlighted: false,
    features: [
      { label: "3 simulações/mês", included: true },
      { label: "Benchmarks públicos", included: true },
      { label: "Comparador (até 2 modelos)", included: true },
      { label: "Comunidade básica", included: true },
      { label: "Analytics pessoal básico", included: true },
      { label: "Simulações ilimitadas", included: false },
      { label: "Exportação de configs (CI/CD)", included: false },
      { label: "Benchmarks privados", included: false },
      { label: "Telemetria avançada", included: false },
      { label: "Suporte prioritário", included: false },
      { label: "API de benchmarking", included: false },
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: { monthly: 29, annual: 23 },
    description: "Para engenheiros e pesquisadores sérios",
    cta: "Iniciar teste grátis 14 dias",
    highlighted: true,
    features: [
      { label: "Simulações ilimitadas", included: true },
      { label: "Benchmarks públicos + privados", included: true },
      { label: "Comparador (até 5 modelos)", included: true },
      { label: "Comunidade completa", included: true },
      { label: "Analytics avançado + relatórios PDF", included: true },
      { label: "Exportação de configs (CI/CD)", included: true },
      { label: "Telemetria avançada de deploy", included: true },
      { label: "Suporte prioritário (24h)", included: true },
      { label: "Benchmarks privados (até 10)", included: true },
      { label: "API de benchmarking", included: false, note: "Team+" },
      { label: "SLA dedicado", included: false, note: "Enterprise" },
    ],
  },
  {
    id: "team",
    name: "Team",
    price: { monthly: 79, annual: 63 },
    description: "Para equipes e pequenas empresas",
    cta: "Teste grátis 14 dias",
    highlighted: false,
    features: [
      { label: "Tudo do Pro", included: true },
      { label: "Até 20 usuários", included: true },
      { label: "Benchmarks privados ilimitados", included: true },
      { label: "API de benchmarking (10k req/mês)", included: true },
      { label: "CI/CD integration (GitHub Actions)", included: true },
      { label: "Dashboard de equipe unificado", included: true },
      { label: "Relatórios comparativos de equipe", included: true },
      { label: "Suporte dedicado (4h)", included: true },
      { label: "Data Marketplace (leitura)", included: true },
      { label: "Data Marketplace (publicação)", included: false, note: "Enterprise" },
      { label: "Onboarding dedicado", included: false, note: "Enterprise" },
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: { monthly: 0, annual: 0 },
    description: "Para organizações com requisitos avançados",
    cta: "Falar com vendas",
    highlighted: false,
    features: [
      { label: "Tudo do Team", included: true },
      { label: "Usuários ilimitados", included: true },
      { label: "API ilimitada + SLA 99.9%", included: true },
      { label: "Data Marketplace (publicação)", included: true },
      { label: "Datasets anonimizados de telemetria", included: true },
      { label: "Consultoria de otimização", included: true },
      { label: "Onboarding dedicado", included: true },
      { label: "SSO / SAML", included: true },
      { label: "Deploy on-premise", included: true },
      { label: "Contrato anual customizado", included: true },
      { label: "Suporte 24/7 + gerente de conta", included: true },
    ],
  },
];

export const PLAN_LIMITS: Record<string, number> = {
  free: 3,
  pro: Infinity,
  team: Infinity,
  enterprise: Infinity,
};
